# -*- coding: utf-8 -*-
"""BNPA Entry Form - Google Sheet (API).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FJ-yhcr6betqKuBadGknvNZHRzdN4rE
"""

import pandas as pd
import numpy as np
import requests
import re
from io import StringIO

api_key = "z8ajshbwdkzwb5qms48ty5w85p8h4wvn4e2mytrh258n7hwwe3a6bm5mcxg806nv"
headers = {
    "x-apikey": api_key,
    "Accept": "application/json"
}
client_id = "4475"
survey_id = "250910" #BNPA
data_format = "json"
url = f"https://sw2.decipherinc.com/api/v1/surveys/selfserve/{client_id}/{survey_id}/data?format={data_format}"

response = requests.get(url, headers=headers)
if response.status_code == 200:
    try:
        data = response.json()
        df = pd.json_normalize(data)
    except Exception as e:
        print("❌ Failed to parse JSON:", str(e))
        print(response.text[:500])

def clean_cast_column(series):
    series = series.replace(["<NA>", "nan", "NaN", "None", ""], pd.NA)
    numeric = pd.to_numeric(series, errors="coerce")
    non_numeric_mask = series.notna() & numeric.isna()
    if non_numeric_mask.any(): return series.astype("string")
    if numeric.notna().any():
        is_all_whole = (numeric.dropna() == numeric.dropna().astype(int)).all()
        has_nulls = numeric.isna().any()
        if is_all_whole and not has_nulls: return numeric.astype("int64")
        else: return numeric.astype("float64")
    return series.astype("string")

df = df.apply(clean_cast_column)
df = df[df['status'] == 3]
df = df.apply(clean_cast_column)

col = "Q2r11oe"
if col not in df.columns:
    df[col] = np.nan
df = df[['uuid', 'Q1r1', 'Q1r2', 'Q1r3', 'Q1r4', 'Q1r5', 'Q1r6', 'Q1r7', 'Q1r8', 'Q1r9', 'QProvincer11', 'Q1_r11r10', 'Q2', 'Q2r11oe',
    'Q3_1', 'Q3_2', 'Q3_3', 'Q3_4', 'Q3_6', 'Q3_7', 'Q3_8', 'Q3_10', 'Q5_1', 'Q3_5', 'Q3_9', 'Q4_2','Q3_image1']]

#Q2
mapping_Q2 = {
    1: "Food & Beverage",
    2: "Beauty",
    3: "Health & Personal Care",
    4: "Household",
    5: "Kids",
    6: "Pet",
    7: "Tech",
    8: "Delivery",
    9: "Financial",
    10: "QSR Menu Item",
    11: "Other:"   # temporary placeholder
}

df["Q2"] = df["Q2"].map(mapping_Q2)
df.loc[df["Q2"] == "Other:", "Q2"] = df["Q2r11oe"]
df = df.drop(columns=["Q2r11oe"])

#Q1
mapping_Q1 = {
    1: 'Alberta',
    2: 'British Columbia',
    3: 'Manitoba',
    4: 'New Brunswick',
    5: 'Newfoundland',
    6: 'Nova Scotia',
    7: 'Ontario',
    8: 'Prince Edward Island',
    9: 'Quebec',
    10: 'Saskatchewan',
    11: 'Northwest Territories',
    12: 'Nunavut',
    13: 'Yukon',
}

df["QProvincer11"] = df["QProvincer11"].map(mapping_Q1)

df["Q5_1"] = df["Q5_1"].map({1: "Yes", 2: "No"})

old_cols = [
    'Q1r1', 'Q1r2', 'Q1r3', 'Q1r4', 'Q1r5', 'Q1r6', 'Q1r7', 'Q1r8', 'Q1r9',
    'QProvincer11', 'Q1_r11r10', 'Q2',
    'Q3_1', 'Q3_2', 'Q3_3', 'Q3_4', 'Q3_6', 'Q3_7', 'Q3_8', 'Q3_10',
    'Q5_1', 'Q3_5', 'Q3_9', 'Q4_3','Q3_image1'
]

new_cols = [
    "First_Name",
    "Last_Name",
    "Email",
    "Company",
    "Title",
    "Phone",
    "Address",
    "Address2",
    "City",
    "Province",
    "Postal_Code",
    "Product_Type",
    "Product_Name",
    "Product_Category",
    "Product_Competitors",
    "Product_Description",
    "Product_Launch_Date",
    "Product_Retail_Price",
    "Product_SKUs",
    "Product_UPC",
    "PO",
    "Innovation_Description",
    "Product_Hero_SKU",
    "Product_link",
    "Product_Image"
]

# Create mapping and rename
rename_map = dict(zip(old_cols, new_cols))
df = df.rename(columns=rename_map)

df = df.replace(["<NA>", "nan"], pd.NA)
df = df.fillna("")

base_url = "https://sw2.decipherinc.com/rep/selfserve/4475/250910:img/"

df["Product_Image"] = df["Product_Image"].apply(
    lambda x: base_url + str(x).replace(" ", "/") if pd.notna(x) and x != "" else ""
)

# --- 0) Auth + setup  ---
import os, re, json, pandas as pd, numpy as np, gspread
from google.oauth2.service_account import Credentials

# Service Account creds from secret
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]
raw = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
if not raw:
    raise RuntimeError("GOOGLE_SERVICE_ACCOUNT_JSON is empty. Add it as a repo secret.")
sa_info = json.loads(raw) if raw.startswith("{") else json.loads(__import__("base64").b64decode(raw).decode("utf-8"))
creds = Credentials.from_service_account_info(sa_info, scopes=SCOPES)
gc = gspread.authorize(creds)

# ---- Sheet ref: ENV > hardcoded fallback ----
SHEET_REF = (os.environ.get("SHEET_URL") or "1U9g_BdnuCtxJar1bcbgOXsgpWpyuxqXeVM7kLnRw23I").strip().strip('"').strip("'")
TAB_NAME  = os.environ.get("TAB_NAME", "Canada")

def open_sheet_by_ref(gc, ref: str):
    # Accept URL or raw ID
    m = re.search(r"/d/([A-Za-z0-9-_]+)", ref)
    key = m.group(1) if m else ref
    return gc.open_by_key(key)

# Open spreadsheet + worksheet (create if missing)
sh = open_sheet_by_ref(gc, SHEET_REF)
try:
    ws = sh.worksheet(TAB_NAME)
except gspread.WorksheetNotFound:
    ws = sh.add_worksheet(title=TAB_NAME, rows=1000, cols=26)

# ---------- helper(s) ----------
def to_sheet_values(df: pd.DataFrame):
    out = df.copy()
    for c in out.columns:
        if pd.api.types.is_integer_dtype(out[c]):
            out[c] = out[c].astype("Float64")
        elif pd.api.types.is_string_dtype(out[c]):
            out[c] = out[c].astype("object")
    out = out.where(pd.notna(out), None).replace(
        {"<NA>": None, "nan": None, "NaN": None, "None": None}
    )
    values = []
    for _, row in out.iterrows():
        cleaned = []
        for x in row.tolist():
            if x is None or x is pd.NA:
                cleaned.append(None)
            elif isinstance(x, float) and np.isnan(x):
                cleaned.append(None)
            elif isinstance(x, str) and x.strip().lower() in ("<na>", "nan", "none"):
                cleaned.append(None)
            else:
                cleaned.append(x)
        values.append(cleaned)
    return values

# OPTIONAL: if your DataFrame has a different uuid column name, map it here
COLUMN_MAPPING = {
    # "UUID": "uuid",
}

# --- 2) Prepare df: apply column mapping & require 'uuid' ---
df = df.rename(columns=COLUMN_MAPPING).copy()
if "uuid" not in df.columns:
    raise ValueError("Your DataFrame must contain a 'uuid' column (rename via COLUMN_MAPPING if needed).")

df["uuid"] = df["uuid"].astype(str)

# --- 3) Blank vs existing sheet ---
headers = ws.row_values(1)  # [] if empty
is_blank = (len(headers) == 0)

if is_blank:
    ordered_cols = ["uuid"] + [c for c in df.columns if c != "uuid"]
    df_to_write = df[ordered_cols]
    headers = df_to_write.columns.tolist()
    values = to_sheet_values(df_to_write)
    ws.clear()
    ws.update("A1", [headers] + values, value_input_option="USER_ENTERED")
else:
    sheet_headers = headers
    for col in sheet_headers:
        if col not in df.columns:
            df[col] = None
    df_aligned = df[sheet_headers]

    first_col_vals = ws.col_values(1)  # includes header
    existing_uuids = set(first_col_vals[1:])

    new_rows = df_aligned[~df_aligned["uuid"].astype(str).isin(existing_uuids)]
    if not new_rows.empty:
        new_rows_values = to_sheet_values(new_rows)
        CHUNK = 500
        for i in range(0, len(new_rows_values), CHUNK):
            ws.append_rows(new_rows_values[i:i+CHUNK], value_input_option="USER_ENTERED")

print("Done. Sheet updated.")
