# -*- coding: utf-8 -*-
"""BNPA Entry Form - Google Sheet (API).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FJ-yhcr6betqKuBadGknvNZHRzdN4rE
"""

import pandas as pd
import numpy as np
import requests
import re
from io import StringIO

api_key = "z8ajshbwdkzwb5qms48ty5w85p8h4wvn4e2mytrh258n7hwwe3a6bm5mcxg806nv"
headers = {
    "x-apikey": api_key,
    "Accept": "application/json"
}
client_id = "4475"
survey_id = "250910" #BNPA
data_format = "json"
url = f"https://sw2.decipherinc.com/api/v1/surveys/selfserve/{client_id}/{survey_id}/data?format={data_format}"

response = requests.get(url, headers=headers)
if response.status_code == 200:
    try:
        data = response.json()
        df = pd.json_normalize(data)
    except Exception as e:
        print("❌ Failed to parse JSON:", str(e))
        print(response.text[:500])

def clean_cast_column(series):
    series = series.replace(["<NA>", "nan", "NaN", "None", ""], pd.NA)
    numeric = pd.to_numeric(series, errors="coerce")
    non_numeric_mask = series.notna() & numeric.isna()
    if non_numeric_mask.any(): return series.astype("string")
    if numeric.notna().any():
        is_all_whole = (numeric.dropna() == numeric.dropna().astype(int)).all()
        has_nulls = numeric.isna().any()
        if is_all_whole and not has_nulls: return numeric.astype("int64")
        else: return numeric.astype("float64")
    return series.astype("string")

df = df.apply(clean_cast_column)
df = df[df['status'] == 3]
df = df.apply(clean_cast_column)

col = "Q2r11oe"
if col not in df.columns:
    df[col] = np.nan
df = df[['uuid', 'Q1r1', 'Q1r2', 'Q1r3', 'Q1r4', 'Q1r5', 'Q1r6', 'Q1r7', 'Q1r8', 'Q1r9', 'QProvincer11', 'Q1_r11r10', 'Q2', 'Q2r11oe',
    'Q3_1', 'Q3_2', 'Q3_3', 'Q3_4', 'Q3_6', 'Q3_7', 'Q3_8', 'Q3_10', 'Q5_1', 'Q3_5', 'Q3_9', 'Q4_2','Q3_image1']]

#Q2
mapping_Q2 = {
    1: "Food & Beverage",
    2: "Beauty",
    3: "Health & Personal Care",
    4: "Household",
    5: "Kids",
    6: "Pet",
    7: "Tech",
    8: "Delivery",
    9: "Financial",
    10: "QSR Menu Item",
    11: "Other:"   # temporary placeholder
}

df["Q2"] = df["Q2"].map(mapping_Q2)
df.loc[df["Q2"] == "Other:", "Q2"] = df["Q2r11oe"]
df = df.drop(columns=["Q2r11oe"])

#Q1
mapping_Q1 = {
    1: 'Alberta',
    2: 'British Columbia',
    3: 'Manitoba',
    4: 'New Brunswick',
    5: 'Newfoundland',
    6: 'Nova Scotia',
    7: 'Ontario',
    8: 'Prince Edward Island',
    9: 'Quebec',
    10: 'Saskatchewan',
    11: 'Northwest Territories',
    12: 'Nunavut',
    13: 'Yukon',
}

df["QProvincer11"] = df["QProvincer11"].map(mapping_Q1)

df["Q5_1"] = df["Q5_1"].map({1: "Yes", 2: "No"})

old_cols = [
    'Q1r1', 'Q1r2', 'Q1r3', 'Q1r4', 'Q1r5', 'Q1r6', 'Q1r7', 'Q1r8', 'Q1r9',
    'QProvincer11', 'Q1_r11r10', 'Q2',
    'Q3_1', 'Q3_2', 'Q3_3', 'Q3_4', 'Q3_6', 'Q3_7', 'Q3_8', 'Q3_10',
    'Q5_1', 'Q3_5', 'Q3_9', 'Q4_3','Q3_image1'
]

new_cols = [
    "First_Name",
    "Last_Name",
    "Email",
    "Company",
    "Title",
    "Phone",
    "Address",
    "Address2",
    "City",
    "Province",
    "Postal_Code",
    "Product_Type",
    "Product_Name",
    "Product_Category",
    "Product_Competitors",
    "Product_Description",
    "Product_Launch_Date",
    "Product_Retail_Price",
    "Product_SKUs",
    "Product_UPC",
    "PO",
    "Innovation_Description",
    "Product_Hero_SKU",
    "Product_link",
    "Product_Image"
]

# Create mapping and rename
rename_map = dict(zip(old_cols, new_cols))
df = df.rename(columns=rename_map)

df = df.replace(["<NA>", "nan"], pd.NA)
df = df.fillna("")

base_url = "https://sw2.decipherinc.com/rep/selfserve/4475/250910:img/"

df["Product_Image"] = df["Product_Image"].apply(
    lambda x: base_url + str(x).replace(" ", "/") if pd.notna(x) and x != "" else ""
)

# --- 0) Auth + setup  ---
import os, re, json, pandas as pd, numpy as np, gspread
from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]
raw = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
if not raw:
    raise RuntimeError("GOOGLE_SERVICE_ACCOUNT_JSON is empty. Add it as a repo secret.")
sa_info = json.loads(raw) if raw.startswith("{") else json.loads(__import__("base64").b64decode(raw).decode("utf-8"))
creds = Credentials.from_service_account_info(sa_info, scopes=SCOPES)
gc = gspread.authorize(creds)

# ---- Sheet ref: ENV > hardcoded fallback ----
SHEET_REF = (os.environ.get("SHEET_URL") or "1U9g_BdnuCtxJar1bcbgOXsgpWpyuxqXeVM7kLnRw23I").strip().strip('"').strip("'")

def open_sheet_by_ref(gc, ref: str):
    m = re.search(r"/d/([A-Za-z0-9-_]+)", ref)
    key = m.group(1) if m else ref
    return gc.open_by_key(key)

sh = open_sheet_by_ref(gc, SHEET_REF)  # open once

# ---------- helper(s) ----------
def to_sheet_values(df: pd.DataFrame):
    out = df.copy()
    for c in out.columns:
        if pd.api.types.is_integer_dtype(out[c]):
            out[c] = out[c].astype("Float64")
        elif pd.api.types.is_string_dtype(out[c]):
            out[c] = out[c].astype("object")
    out = out.where(pd.notna(out), None).replace(
        {"<NA>": None, "nan": None, "NaN": None, "None": None}
    )
    values = []
    for _, row in out.iterrows():
        cleaned = []
        for x in row.tolist():
            if x is None or x is pd.NA:
                cleaned.append(None)
            elif isinstance(x, float) and np.isnan(x):
                cleaned.append(None)
            elif isinstance(x, str) and x.strip().lower() in ("<na>", "nan", "none"):
                cleaned.append(None)
            else:
                cleaned.append(x)
        values.append(cleaned)
    return values

def write_new_rows_by_key(sh, tab_name: str, df: pd.DataFrame, key_col="uuid", column_mapping=None) -> int:
    """
    Create tab if missing. If tab is blank: write headers + all rows.
    Else: align to existing headers and append only new rows by key_col.
    Returns number of rows written/appended. Skips if df is empty.
    """
    if df is None or df.empty:
        return 0

    if column_mapping:
        df = df.rename(columns=column_mapping).copy()

    if key_col not in df.columns:
        raise ValueError(f"DataFrame must include key column '{key_col}'")

    # normalize key to string (and strip whitespace just in case)
    df[key_col] = df[key_col].astype(str).str.strip()

    try:
        ws = sh.worksheet(tab_name)
    except gspread.WorksheetNotFound:
        ws = sh.add_worksheet(title=tab_name, rows=1000, cols=26)

    headers = ws.row_values(1)

    if not headers:
        # blank tab: put key first, then the rest
        ordered = [key_col] + [c for c in df.columns if c != key_col]
        df_to_write = df[ordered]
        ws.clear()
        ws.update("A1", [df_to_write.columns.tolist()] + to_sheet_values(df_to_write),
                  value_input_option="USER_ENTERED")
        return len(df_to_write)

    # align df to existing headers (add missing as blank; drop extras)
    for col in headers:
        if col not in df.columns:
            df[col] = None
    df = df[headers]

    # existing keys (assumes key is in column A)
    existing_keys = set(v.strip() for v in ws.col_values(1)[1:])  # skip header + trim
    new_rows = df[~df[key_col].astype(str).str.strip().isin(existing_keys)]
    if new_rows.empty:
        return 0

    values = to_sheet_values(new_rows)
    CHUNK = 500
    for i in range(0, len(values), CHUNK):
        ws.append_rows(values[i:i+CHUNK], value_input_option="USER_ENTERED")
    return len(new_rows)

# ---------- calls for your three datasets ----------
# Assumes df_can, df_usa, df_new are built above and include 'uuid'
results = []

try:
    n_can = write_new_rows_by_key(sh, "Canada", df_can, key_col="uuid")
    results.append(f"Canada: +{n_can} rows")
except Exception as e:
    results.append(f"Canada: ERROR {e}")

try:
    n_usa = write_new_rows_by_key(sh, "USA", df_usa, key_col="uuid")
    results.append(f"USA: +{n_usa} rows")
except Exception as e:
    results.append(f"USA: ERROR {e}")

try:
    n_new = write_new_rows_by_key(sh, "New & Noteworthy", df_new, key_col="uuid")
    results.append(f"New & Noteworthy: +{n_new} rows")
except Exception as e:
    results.append(f"New & Noteworthy: ERROR {e}")

print(" | ".join(results))
